### ISSUE TITLE
CSS not being applied with same priorities

### ISSUE THREAD

**Issue by szicari-streambit** [matheus23/elm-tailwind-modules#7]
I am attempting to use Tailwind UI components with `elm-tailwind-modules` but finding inconsistencies that seem to come down to CSS styles being incorrectly overridden. I cannot quite figure out what's going on, but the problem seems to be either the order that the CSS is put into the document, or something related to the generated Tailwind CSS classes. Any insights would be greatly appreciated.

Here is an example:

This is my component, rendered by Elm:

<img width="498" alt="Screen Shot 2021-07-17 at 5 18 17 PM" src="https://user-images.githubusercontent.com/80933567/126050462-42151514-7df0-4f55-bcda-db10738da451.png">

This is how the element is _supposed_ to appear:

<img width="518" alt="Screen Shot 2021-07-17 at 5 18 50 PM" src="https://user-images.githubusercontent.com/80933567/126050476-0e4552dc-693f-4690-b5bc-d8fbd12aa518.png">

Note that the inputs are rounded in the correct example but square in the Elm-rendered code. Looking at the styles, it's clear the CSS is in the wrong priority:

**Elm-Rendered Styles, applied**

<img width="401" alt="Screen Shot 2021-07-17 at 5 20 23 PM" src="https://user-images.githubusercontent.com/80933567/126050497-58e20aee-996f-45b2-b54b-6771ed4e491a.png">

**Tailwind UI Components Styles, applied**

<img width="392" alt="Screen Shot 2021-07-17 at 5 20 54 PM" src="https://user-images.githubusercontent.com/80933567/126050507-a0b90c3d-be04-42dd-ac54-99815418de84.png">

I am happy to answer questions, but I do not have any further insight beyond what I showed here.

**Comment by matheus23** [comment]
Yeah, tailwindcss relies on the ordering of css declarations *in the generated css file*.

Unfortunately, we can't do this in elm-tailwind-modules, because we're not generating a single css file.
Thus, sometimes styles are overwritten in the opposite order than they are in tailwindcss.

A workaround for your specific case is to use the [`class` strategy for the tailwindcss/forms plugin](https://github.com/tailwindlabs/tailwindcss-forms#using-classes-instead-of-element-selectors).
Then, you'll need to attach add explicit styles to your form inputs (e.g. `Tw.form_input` or `Tw.form_checkbox`), but you'll be able to control how they override each other via ordering your styles.

(Just linking someone else who had a similar issue for personal reference: https://discourse.elm-lang.org/t/matheus23-elm-tailwind-modules-and-formcheckbox/7281)

**Comment by szicari-streambit** [comment]
Thank you for this info! I'll close out the ticket, as it sounds like this issue has been amply covered.

**Comment by matheus23** [comment]
Great! Let me know how it goes: Does the workaround work for you and address your use case?

**Comment by szicari-streambit** [comment]
I haven't tried it yet. I had a tight deadline and couldn't continue trying to figure it out. I really appreciate your response and am looking forward to giving it a try during the next phase of my project.

**Comment by matheus23** [comment]
Allow me to rename this issue for better discoverability

**Comment by szicari-streambit** [comment]
Please do!
